// FateWise — Client-side Pro status detection
// Checks localStorage for token + expiry to determine upgrade eligibility

const FATEWISE_PRO_KEY = 'fatewise_pro';
const FATEWISE_TOKEN_KEY = 'fatewise_token';

/**
 * Check if the current user has an active Pro subscription.
 * Reads from localStorage where tokens are stored after login/signup auto-detect.
 */
export function isProUser(): boolean {
  if (typeof window === 'undefined') return false;

  const token = localStorage.getItem(FATEWISE_TOKEN_KEY);
  if (!token) return false;

  // Check for explicit pro flag (set after Gumroad purchase verification)
  const proFlag = localStorage.getItem(FATEWISE_PRO_KEY);
  if (proFlag === 'true') return true;

  // If token exists but no pro flag, check if it looks like a valid FateWise token
  // fw-* tokens are generated by createFatewiseToken() for pro/premium users
  if (token.startsWith('fw-')) {
    // Valid FateWise token → likely pro user
    return true;
  }

  return false;
}

/**
 * Get the user's plan type ('pro', 'premium', or null)
 */
export function getProPlan(): 'pro' | 'premium' | null {
  if (typeof window === 'undefined') return null;

  const plan = localStorage.getItem(FATEWISE_PRO_KEY + '_plan');
  if (plan === 'pro' || plan === 'premium') return plan;

  // Infer from token
  const token = localStorage.getItem(FATEWISE_TOKEN_KEY);
  if (token?.startsWith('fw-')) return 'pro'; // default to pro

  return null;
}

/**
 * Mark user as Pro (called after Gumroad purchase verification)
 */
export function markAsPro(plan: 'pro' | 'premium' = 'pro'): void {
  if (typeof window === 'undefined') return;

  localStorage.setItem(FATEWISE_PRO_KEY, 'true');
  localStorage.setItem(FATEWISE_PRO_KEY + '_plan', plan);

  // Set expiry based on plan
  const now = Date.now();
  if (plan === 'pro') {
    // Pro monthly: 30 days
    localStorage.setItem(FATEWISE_PRO_KEY + '_expires', String(now + 30 * 24 * 60 * 60 * 1000));
  } else {
    // Premium: lifetime
    localStorage.setItem(FATEWISE_PRO_KEY + '_expires', '0');
  }
}

/**
 * Check if Pro subscription has expired
 */
export function isProExpired(): boolean {
  if (typeof window === 'undefined') return true;

  const expires = localStorage.getItem(FATEWISE_PRO_KEY + '_expires');
  if (!expires || expires === '0') return false;

  const expiryDate = Number(expires);
  if (expiryDate === 0) return false;

  return Date.now() > expiryDate;
}
